/** Prénoms clairement féminins (FR / RDC) — pour corriger un sexe M erroné. */
const FEMININE_GIVEN_NAMES = new Set([
  'ADA',
  'AGNES',
  'AIMEE',
  'ALICE',
  'AMINA',
  'ANDREE',
  'ANGE',
  'ANGELIQUE',
  'ANNA',
  'ANNE',
  'ANTOINETTE',
  'AURELIE',
  'BEATRICE',
  'BENEDICTE',
  'BERNADETTE',
  'BIENVENUE',
  'BLANDINE',
  'BRIGITTE',
  'CAROLE',
  'CAROLINE',
  'CARROLE',
  'CATHERINE',
  'CECILE',
  'CELESTINE',
  'CHANTAL',
  'CHARLENE',
  'CHARLINE',
  'CHRISTELLE',
  'CHRISTINE',
  'CLAIRE',
  'CLAUDINE',
  'CLAUDETTE',
  'COLETTE',
  'CONSOLATA',
  'CONSOLATE',
  'CYNTIA',
  'CYNTICHE',
  'CYNTHIA',
  'DANIELLE',
  'DEBORAH',
  'DELPHINE',
  'DENISE',
  'DIANE',
  'DIEUMERCI',
  'DIVINE',
  'DORCAS',
  'EDITH',
  'ELIANE',
  'ELISA',
  'ELISABETH',
  'ELIZABETH',
  'ELODIE',
  'EMILIE',
  'EMMANUELLE',
  'ESTELLE',
  'ESTHER',
  'EUGENIE',
  'EUNICE',
  'EVA',
  'EVELYNE',
  'FABIENNE',
  'FAUSTINE',
  'FELICITE',
  'FLEUR',
  'FLEURETTE',
  'FLORENCE',
  'FORTUNA',
  'FOSTINE',
  'FRANCINE',
  'FRANCOISE',
  'GABRIELLE',
  'GAELLE',
  'GENEVIEVE',
  'GEORGETTE',
  'GERMAINE',
  'GHISLAINE',
  'GINETTE',
  'GISELE',
  'GLORIA',
  'GRACIA',
  'HANNA',
  'HANNAH',
  'HELENE',
  'HENRIETTE',
  'HONORINE',
  'HORTENSE',
  'IDA',
  'INES',
  'INGRID',
  'IRENE',
  'ISABELLE',
  'JACQUELINE',
  'JEANNE',
  'JEANNETTE',
  'JEANNINE',
  'JESSICA',
  'JOCELYNE',
  'JOSEPHINE',
  'JOSETTE',
  'JOSIANE',
  'JUDITH',
  'JULIE',
  'JULIETTE',
  'JUSTINE',
  'LADIE',
  'LAETITIA',
  'LAURA',
  'LAURE',
  'LAURENCE',
  'LEA',
  'LEILA',
  'LILIANE',
  'LINDA',
  'LOIS',
  'LOUISE',
  'LUCIE',
  'MADELEINE',
  'MADELENE',
  'MAGALI',
  'MAGALIE',
  'MARCELINE',
  'MARGUERITE',
  'MARGUERITTE',
  'MARIA',
  'MARIANNE',
  'MARIE',
  'MARIELLE',
  'MARIETTE',
  'MARINA',
  'MARLENE',
  'MARTHA',
  'MARTHE',
  'MARTINE',
  'MARY',
  'MELANIE',
  'MICHELE',
  'MICHELINE',
  'MICHILINE',
  'MIRIAM',
  'MONIQUE',
  'MYRIAM',
  'NADIA',
  'NADINE',
  'NAOMI',
  'NAOMIE',
  'NATHALIE',
  'NICOLE',
  'NINA',
  'NOELLE',
  'NOEMIE',
  'ODETTE',
  'ODILE',
  'OLIVIA',
  'PASCALE',
  'PASCALINE',
  'PATRICIA',
  'PAULETTE',
  'PAULINE',
  'PHILOMENE',
  'PRECIEUSE',
  'PRISCA',
  'PRISCILLE',
  'RACHEL',
  'RAPHAELLE',
  'REBECCA',
  'REGINA',
  'REINE',
  'RITA',
  'ROSALIE',
  'ROSE',
  'ROSELINE',
  'ROSETTE',
  'ROSINE',
  'RUTH',
  'SABINE',
  'SABRINA',
  'SALOME',
  'SANDRA',
  'SANDRINE',
  'SARA',
  'SARAH',
  'SERAPHINE',
  'SHEKINAH',
  'SIMONE',
  'SOLANGE',
  'SONIA',
  'SOPHIE',
  'STELLA',
  'STEPHANIE',
  'SUZANNE',
  'SYLVIE',
  'TABITHA',
  'TANTINE',
  'TENTINE',
  'THERESE',
  'VALENTINE',
  'VALERIE',
  'VANESSA',
  'VERONIQUE',
  'VERRONIQUE',
  'VICTOIRE',
  'VICTORIA',
  'VICTORINE',
  'VIOLETTE',
  'VIRGINIE',
  'VIVIANE',
  'YOLANDE',
  'YVETTE',
  'YVONNE',
  'ZITA',
  'ZOE',
]);

/** Prénoms masculins fréquents — évite de prendre un nom de famille pour un prénom. */
const MALE_GIVEN_NAMES = new Set([
  'AARON',
  'ALAIN',
  'ALEXANDRE',
  'ALPHONSE',
  'ANDRE',
  'ARISTOTE',
  'AUGUSTIN',
  'BENJAMIN',
  'BERNARD',
  'BERTIN',
  'BIENVENU',
  'BLAISE',
  'BOB',
  'CEDRIC',
  'CEDRICK',
  'CHADRACK',
  'CHRISTIAN',
  'CHRISTOPHE',
  'CLAUDE',
  'CLEMENT',
  'DANIEL',
  'DAVID',
  'DIDIER',
  'DIEU',
  'DONATIEN',
  'EDOUARD',
  'EMILE',
  'EMMANUEL',
  'ERIC',
  'ERICK',
  'ESAIE',
  'ETIENNE',
  'EUGENE',
  'FABRICE',
  'FELIX',
  'FLAVIEN',
  'FRANCK',
  'FRANCIS',
  'FRANCOIS',
  'FREDDY',
  'GABRIEL',
  'GASTON',
  'GAUTHIER',
  'GILBERT',
  'GLODY',
  'GUELORD',
  'GUILLAUME',
  'GUYLAIN',
  'HENRI',
  'HERVE',
  'HUGUES',
  'IBRAHIM',
  'INNOCENT',
  'ISAAC',
  'JACQUES',
  'JAPHET',
  'JEAN',
  'JEREMIE',
  'JIMMY',
  'JOEL',
  'JOHN',
  'JONAS',
  'JONATHAN',
  'JOSEPH',
  'JOSUE',
  'JUNIOR',
  'LOUIS',
  'LUC',
  'MARC',
  'MARCEL',
  'MICHEL',
  'MICHAEL',
  'MIKE',
  'NOEL',
  'OLIVIER',
  'OSCAR',
  'PAPY',
  'PASCAL',
  'PATRICK',
  'PAUL',
  'PHILIPPE',
  'PIERRE',
  'RAPHAEL',
  'RICHARD',
  'ROBERT',
  'RODRIGUE',
  'ROGER',
  'SAMUEL',
  'SEBASTIEN',
  'SERGE',
  'SIMON',
  'STANISLAS',
  'THOMAS',
  'TRESOR',
  'VICTOR',
  'WILLIAM',
]);

function foldNameToken(token: string): string {
  return token
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toUpperCase()
    .replace(/[^A-Z]/g, '');
}

function tokensOf(nom: string): string[] {
  return nom
    .trim()
    .split(/[\s]+/)
    .map((part) => part.trim())
    .filter(Boolean);
}

function partsOfToken(token: string): string[] {
  return token
    .split(/[-/]/)
    .map(foldNameToken)
    .filter(Boolean);
}

function isFeminineToken(folded: string): boolean {
  return FEMININE_GIVEN_NAMES.has(folded);
}

function isMaleToken(folded: string): boolean {
  return MALE_GIVEN_NAMES.has(folded);
}

/** True si le nom contient un prénom féminin identifiable. */
export function hasFeminineGivenName(nom: string): boolean {
  const tokens = tokensOf(nom);
  if (!tokens.length) return false;

  const lastToken = tokens[tokens.length - 1]!;
  const lastFolded = foldNameToken(lastToken);
  if (isFeminineToken(lastFolded)) return true;

  const lastParts = partsOfToken(lastToken);
  if (lastParts.some(isFeminineToken) && !lastParts.some(isMaleToken)) {
    return true;
  }

  const firstParts = partsOfToken(tokens[0]!);
  const lastIsMale = lastParts.some(isMaleToken);
  if (!lastIsMale && firstParts.some(isFeminineToken) && !firstParts.some(isMaleToken)) {
    return true;
  }

  return false;
}

/** Passe M / vide → F lorsque le prénom est féminin. Ne touche pas un F déjà correct. */
export function inferFemaleSexeFromName<T extends string>(
  nom: string,
  sexe: T | '',
): T | 'F' | '' {
  if (sexe === 'F') return sexe;
  if (hasFeminineGivenName(nom)) return 'F';
  return sexe;
}
