export interface AirportOption {
  iata: string;
  label: string;
}

export interface AirlineOption {
  label: string;
}

export const TRAVEL_AIRPORTS: AirportOption[] = [
  { iata: 'FIH', label: "Kinshasa N'djili" },
  { iata: 'FBM', label: 'Lubumbashi Luano' },
  { iata: 'GOM', label: 'Goma International' },
  { iata: 'BKY', label: 'Bukavu Kavumu' },
  { iata: 'FKI', label: 'Kisangani Bangoka' },
  { iata: 'KGA', label: 'Kananga' },
  { iata: 'MJM', label: 'Mbuji-Mayi' },
  { iata: 'BUX', label: 'Bunia' },
  { iata: 'IRP', label: 'Isiro Matari' },
  { iata: 'BKO', label: 'Bamako Senou' },
  { iata: 'ABJ', label: 'Abidjan Félix Houphouët-Boigny' },
  { iata: 'ACC', label: 'Accra Kotoka' },
  { iata: 'LOS', label: 'Lagos Murtala Muhammed' },
  { iata: 'NBO', label: 'Nairobi Jomo Kenyatta' },
  { iata: 'JNB', label: 'Johannesburg OR Tambo' },
  { iata: 'CPT', label: 'Cape Town International' },
  { iata: 'DAR', label: 'Dar es Salaam Julius Nyerere' },
  { iata: 'ADD', label: 'Addis Ababa Bole' },
  { iata: 'CAI', label: 'Cairo International' },
  { iata: 'CMN', label: 'Casablanca Mohammed V' },
  { iata: 'TUN', label: 'Tunis Carthage' },
  { iata: 'ALG', label: 'Algiers Houari Boumediene' },
  { iata: 'DKR', label: 'Dakar Blaise Diagne' },
  { iata: 'LAD', label: 'Luanda Quatro de Fevereiro' },
  { iata: 'LUN', label: 'Lusaka Kenneth Kaunda' },
  { iata: 'HRE', label: 'Harare International' },
  { iata: 'KGL', label: 'Kigali International' },
  { iata: 'EBB', label: 'Entebbe International' },
  { iata: 'CDG', label: 'Paris Charles de Gaulle' },
  { iata: 'ORY', label: 'Paris Orly' },
  { iata: 'LHR', label: 'London Heathrow' },
  { iata: 'LGW', label: 'London Gatwick' },
  { iata: 'AMS', label: 'Amsterdam Schiphol' },
  { iata: 'BRU', label: 'Brussels Airport' },
  { iata: 'FRA', label: 'Frankfurt am Main' },
  { iata: 'MUC', label: 'Munich Airport' },
  { iata: 'ZRH', label: 'Zurich Airport' },
  { iata: 'GVA', label: 'Geneva Airport' },
  { iata: 'MAD', label: 'Madrid Barajas' },
  { iata: 'BCN', label: 'Barcelona El Prat' },
  { iata: 'FCO', label: 'Rome Fiumicino' },
  { iata: 'MXP', label: 'Milan Malpensa' },
  { iata: 'IST', label: 'Istanbul Airport' },
  { iata: 'SAW', label: 'Istanbul Sabiha Gökçen' },
  { iata: 'DXB', label: 'Dubai International' },
  { iata: 'AUH', label: 'Abu Dhabi International' },
  { iata: 'DOH', label: 'Doha Hamad International' },
  { iata: 'JED', label: 'Jeddah King Abdulaziz' },
  { iata: 'RUH', label: 'Riyadh King Khalid' },
  { iata: 'DEL', label: 'Delhi Indira Gandhi' },
  { iata: 'BOM', label: 'Mumbai Chhatrapati Shivaji' },
  { iata: 'PEK', label: 'Beijing Capital' },
  { iata: 'PVG', label: 'Shanghai Pudong' },
  { iata: 'HKG', label: 'Hong Kong International' },
  { iata: 'SIN', label: 'Singapore Changi' },
  { iata: 'BKK', label: 'Bangkok Suvarnabhumi' },
  { iata: 'KUL', label: 'Kuala Lumpur International' },
  { iata: 'NRT', label: 'Tokyo Narita' },
  { iata: 'HND', label: 'Tokyo Haneda' },
  { iata: 'ICN', label: 'Seoul Incheon' },
  { iata: 'SYD', label: 'Sydney Kingsford Smith' },
  { iata: 'MEL', label: 'Melbourne Tullamarine' },
  { iata: 'JFK', label: 'New York JFK' },
  { iata: 'EWR', label: 'Newark Liberty' },
  { iata: 'LGA', label: 'New York LaGuardia' },
  { iata: 'IAD', label: 'Washington Dulles' },
  { iata: 'DCA', label: 'Washington Reagan National' },
  { iata: 'ORD', label: "Chicago O'Hare" },
  { iata: 'ATL', label: 'Atlanta Hartsfield-Jackson' },
  { iata: 'MIA', label: 'Miami International' },
  { iata: 'DFW', label: 'Dallas Fort Worth' },
  { iata: 'LAX', label: 'Los Angeles International' },
  { iata: 'SFO', label: 'San Francisco International' },
  { iata: 'SEA', label: 'Seattle Tacoma' },
  { iata: 'YYZ', label: 'Toronto Pearson' },
  { iata: 'YUL', label: 'Montreal Trudeau' },
  { iata: 'YVR', label: 'Vancouver International' },
  { iata: 'GRU', label: 'São Paulo Guarulhos' },
  { iata: 'GIG', label: 'Rio de Janeiro Galeão' },
  { iata: 'EZE', label: 'Buenos Aires Ezeiza' },
  { iata: 'BOG', label: 'Bogotá El Dorado' },
  { iata: 'LIM', label: 'Lima Jorge Chávez' },
  { iata: 'SCL', label: 'Santiago Arturo Merino Benítez' },
  { iata: 'VIE', label: 'Vienna International' },
  { iata: 'PRG', label: 'Prague Václav Havel' },
  { iata: 'WAW', label: 'Warsaw Chopin' },
  { iata: 'CPH', label: 'Copenhagen Kastrup' },
  { iata: 'ARN', label: 'Stockholm Arlanda' },
  { iata: 'OSL', label: 'Oslo Gardermoen' },
  { iata: 'HEL', label: 'Helsinki Vantaa' },
  { iata: 'DUB', label: 'Dublin Airport' },
  { iata: 'LIS', label: 'Lisbon Humberto Delgado' },
  { iata: 'ATH', label: 'Athens International' },
  { iata: 'OTP', label: 'Bucharest Henri Coandă' },
  { iata: 'BUD', label: 'Budapest Ferenc Liszt' },
  { iata: 'KBP', label: 'Kyiv Boryspil' },
  { iata: 'TLV', label: 'Tel Aviv Ben Gurion' },
  { iata: 'AMM', label: 'Amman Queen Alia' },
  { iata: 'BEY', label: 'Beirut Rafic Hariri' },
  { iata: 'KWI', label: 'Kuwait International' },
  { iata: 'BAH', label: 'Bahrain International' },
  { iata: 'MCT', label: 'Muscat International' },
  { iata: 'ISB', label: 'Islamabad International' },
  { iata: 'KHI', label: 'Karachi Jinnah' },
  { iata: 'DAC', label: 'Dhaka Hazrat Shahjalal' },
  { iata: 'CGK', label: 'Jakarta Soekarno-Hatta' },
  { iata: 'MNL', label: 'Manila Ninoy Aquino' },
  { iata: 'SGN', label: 'Ho Chi Minh City Tan Son Nhat' },
  { iata: 'HAN', label: 'Hanoi Noi Bai' },
  { iata: 'TPE', label: 'Taipei Taoyuan' },
  { iata: 'AKL', label: 'Auckland Airport' },
  { iata: 'DSS', label: 'Dakar Blaise Diagne' },
  { iata: 'OUA', label: 'Ouagadougou' },
  { iata: 'NIM', label: 'Niamey Diori Hamani' },
  { iata: 'NDJ', label: "N'Djamena International" },
  { iata: 'BGF', label: 'Bangui M\'Poko' },
  { iata: 'BZV', label: 'Brazzaville Maya-Maya' },
  { iata: 'PNR', label: 'Pointe-Noire' },
  { iata: 'LBV', label: 'Libreville Leon M\'ba' },
  { iata: 'DLA', label: 'Douala International' },
  { iata: 'NSI', label: 'Yaoundé Nsimalen' },
  { iata: 'BJM', label: 'Bujumbura International' },
  { iata: 'MPM', label: 'Maputo International' },
  { iata: 'WDH', label: 'Windhoek Hosea Kutako' },
  { iata: 'GBE', label: 'Gaborone Sir Seretse Khama' },
  { iata: 'MRU', label: 'Mauritius Sir Seewoosagur Ramgoolam' },
  { iata: 'RUN', label: 'Saint-Denis Roland Garros' },
  { iata: 'TNR', label: 'Antananarivo Ivato' },
  { iata: 'DZA', label: 'Dzaoudzi Pamandzi' },
];

export const TRAVEL_AIRLINES: AirlineOption[] = [
  { label: 'Ethiopian Airlines' },
  { label: 'Kenya Airways' },
  { label: 'South African Airways' },
  { label: 'EgyptAir' },
  { label: 'Royal Air Maroc' },
  { label: 'Air Algérie' },
  { label: 'Tunisair' },
  { label: 'Air Senegal' },
  { label: 'ASKY Airlines' },
  { label: 'RwandAir' },
  { label: 'Uganda Airlines' },
  { label: 'TAAG Angola Airlines' },
  { label: 'Air Côte d\'Ivoire' },
  { label: 'Air France' },
  { label: 'KLM Royal Dutch Airlines' },
  { label: 'Brussels Airlines' },
  { label: 'Lufthansa' },
  { label: 'Swiss International Air Lines' },
  { label: 'British Airways' },
  { label: 'Virgin Atlantic' },
  { label: 'Iberia' },
  { label: 'ITA Airways' },
  { label: 'Turkish Airlines' },
  { label: 'Emirates' },
  { label: 'Qatar Airways' },
  { label: 'Etihad Airways' },
  { label: 'Saudia' },
  { label: 'Oman Air' },
  { label: 'Gulf Air' },
  { label: 'Kuwait Airways' },
  { label: 'Delta Air Lines' },
  { label: 'United Airlines' },
  { label: 'American Airlines' },
  { label: 'Air Canada' },
  { label: 'LATAM Airlines' },
  { label: 'Avianca' },
  { label: 'Copa Airlines' },
  { label: 'Singapore Airlines' },
  { label: 'Cathay Pacific' },
  { label: 'Japan Airlines' },
  { label: 'All Nippon Airways (ANA)' },
  { label: 'Korean Air' },
  { label: 'China Southern Airlines' },
  { label: 'China Eastern Airlines' },
  { label: 'Air China' },
  { label: 'Thai Airways' },
  { label: 'Malaysia Airlines' },
  { label: 'Garuda Indonesia' },
  { label: 'Qantas' },
  { label: 'Congo Airways' },
  { label: 'Precision Air' },
  { label: 'Air Tanzania' },
  { label: 'Mauritania Airlines' },
  { label: 'Camair-Co' },
  { label: 'Air Burkina' },
  { label: 'Air Mali' },
  { label: 'Air Zimbabwe' },
  { label: 'Proflight Zambia' },
  { label: 'Fastjet' },
  { label: 'FlyDubai' },
  { label: 'Pegasus Airlines' },
  { label: 'Ryanair' },
  { label: 'easyJet' },
  { label: 'Vueling' },
  { label: 'Transavia' },
  { label: 'Norwegian Air Shuttle' },
  { label: 'Finnair' },
  { label: 'SAS Scandinavian Airlines' },
  { label: 'Austrian Airlines' },
  { label: 'TAP Air Portugal' },
  { label: 'Aegean Airlines' },
  { label: 'El Al' },
  { label: 'Middle East Airlines' },
  { label: 'Royal Jordanian' },
  { label: 'Air India' },
  { label: 'IndiGo' },
  { label: 'Vistara' },
];

export const SEAT_PREFERENCE_OPTIONS = ['Window', 'Aisle', 'Middle', 'No preference'] as const;

function uniqueLabels(labels: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const label of labels) {
    if (seen.has(label)) continue;
    seen.add(label);
    result.push(label);
  }
  return result;
}

export const TRAVEL_AIRLINE_LABELS = uniqueLabels(TRAVEL_AIRLINES.map((airline) => airline.label));

export function formatAirportOption(airport: AirportOption): string {
  return `${airport.iata} — ${airport.label}`;
}

export function filterAirportOptions(query: string, limit = 12): string[] {
  const normalized = query.trim().toLowerCase();
  const matches = TRAVEL_AIRPORTS.filter((airport) => {
    const label = formatAirportOption(airport).toLowerCase();
    return !normalized || label.includes(normalized) || airport.iata.toLowerCase().includes(normalized);
  });
  return matches.slice(0, limit).map(formatAirportOption);
}

export function filterAirlineOptions(query: string, limit = 12): string[] {
  const normalized = query.trim().toLowerCase();
  return uniqueLabels(
    TRAVEL_AIRLINES.filter(
      (airline) => !normalized || airline.label.toLowerCase().includes(normalized),
    ).map((airline) => airline.label),
  ).slice(0, limit);
}
