/**
 * Affectations logement village issues de la liste « Mson N° / OCCUPANTS / TYPE ».
 * Les noms sont volontairement approximatifs — matching flou côté import.
 */
export interface VillageHousingAssignmentSeed {
  numero: string;
  occupant: string;
  typeMaison: string;
}

export const VILLAGE_HOUSING_ASSIGNMENTS: VillageHousingAssignmentSeed[] = [
  { numero: '1', occupant: 'Jack ILONDO', typeMaison: 'High Standard' },
  { numero: '2', occupant: 'Elias TANUI', typeMaison: 'High Standard' },
  { numero: '3', occupant: 'Michel KABEYA', typeMaison: 'High Standard' },
  { numero: '4', occupant: 'Andrew Malonga', typeMaison: 'High Standard' },
  { numero: '5', occupant: '', typeMaison: 'Free Style' },
  { numero: '6', occupant: '', typeMaison: 'Free Style' },
  { numero: '7', occupant: 'Pelagie Kinkinia', typeMaison: 'Free Style' },
  { numero: '8', occupant: 'Simon MACHARIA', typeMaison: 'Free Style' },
  { numero: '9', occupant: 'Joel ADHULE', typeMaison: 'Free Style' },
  { numero: '10', occupant: 'Yvan ILUNGA', typeMaison: 'Free Style' },
  { numero: '11', occupant: 'LM ETEME', typeMaison: 'Free Style' },
  { numero: '12', occupant: 'Marques Mungwe', typeMaison: 'Free Style' },
  { numero: '13', occupant: 'Nursery School', typeMaison: 'Free Style' },
  { numero: '14', occupant: 'Giscard RUKOMEZA', typeMaison: 'Free Style' },
  { numero: '15', occupant: 'Emmanuel Lisangola', typeMaison: 'Free Style' },
  { numero: '16', occupant: 'Leonard Mutombo', typeMaison: 'Free Style' },
  { numero: '17', occupant: 'Serge MUAKASA', typeMaison: 'Free Style' },
  { numero: '18', occupant: 'Ruffin Mpay', typeMaison: 'Free Style' },
  { numero: '19', occupant: 'Nelson Mayumbu', typeMaison: 'Free Style' },
  { numero: '20', occupant: '', typeMaison: 'Free Style' },
  { numero: '21', occupant: 'Charles PONGO PONGO', typeMaison: 'Free Style' },
  { numero: '22', occupant: 'Pero', typeMaison: 'Free Style' },
  { numero: '23', occupant: 'Patrick MUKENDI', typeMaison: 'Free Style' },
  { numero: '24', occupant: 'Parician UUCHI', typeMaison: 'Twins' },
  { numero: '25', occupant: 'Jeremie MUBA', typeMaison: 'Twins' },
  { numero: '26 A', occupant: 'Nadege NSILU', typeMaison: 'Studio' },
  { numero: '26 B', occupant: '', typeMaison: 'Studio' },
  { numero: '27 A', occupant: 'Oxano', typeMaison: 'Studio' },
  { numero: '27 B', occupant: 'Noel Ndonga', typeMaison: 'Studio' },
  { numero: '28 A', occupant: 'HORNEL', typeMaison: 'Studio' },
  { numero: '28 B', occupant: 'Archipp Mulenda', typeMaison: 'Studio' },
  { numero: '29 A', occupant: 'Leon Badibanga', typeMaison: 'Studio' },
  { numero: '30', occupant: 'Nathan IT', typeMaison: 'Twins' },
  { numero: '31', occupant: 'Fred moleka', typeMaison: 'Twins' },
  { numero: '32', occupant: 'Patrick KAHASHA', typeMaison: 'Twins' },
  { numero: '33', occupant: 'Jean Rostand', typeMaison: 'Twins' },
  { numero: '34', occupant: 'Hervey Sabi', typeMaison: 'Twins' },
  { numero: '35', occupant: 'Christian Kuabi', typeMaison: 'Twins' },
  { numero: '36', occupant: 'Jisca Muanda', typeMaison: 'Twins' },
  { numero: '37', occupant: 'LUZOLO NSEMBOLO', typeMaison: 'Twins' },
  { numero: '38', occupant: 'Karine MVUTU', typeMaison: 'Twins' },
  { numero: '39', occupant: 'Ovie TULOMBA', typeMaison: 'Twins' },
  { numero: '42', occupant: 'Yannick KALAMBAY', typeMaison: 'Twins' },
  { numero: '43', occupant: 'RODRIGUE', typeMaison: 'Twins' },
  { numero: '44', occupant: 'Sosthene KAMANDA', typeMaison: 'Twins' },
  { numero: '45', occupant: '', typeMaison: 'Twins' },
  { numero: '46', occupant: 'TANDU NKWALA BERTIN', typeMaison: 'Twins' },
  { numero: '47', occupant: 'MALU', typeMaison: 'Twins' },
  { numero: '48', occupant: 'Leon Mpongo', typeMaison: 'Twins' },
  { numero: '49', occupant: 'Romuald', typeMaison: 'Twins' },
  { numero: '50', occupant: 'REAGEAN TULENGI', typeMaison: 'Twins' },
  { numero: '51', occupant: 'Jonas LINGOMA', typeMaison: 'Twins' },
  { numero: '52', occupant: 'RAMSES KALUNGA', typeMaison: 'Twins' },
  { numero: '53', occupant: 'Joel TABILA', typeMaison: 'Twins' },
  { numero: '54', occupant: 'Hassan Kananga', typeMaison: 'Twins' },
  { numero: '55', occupant: 'ERICK NLANDU', typeMaison: 'Twins' },
  { numero: '56', occupant: 'ZOLA LONGO', typeMaison: 'Twins' },
  { numero: '57', occupant: 'CHARLIE KABANGU', typeMaison: 'Twins' },
  { numero: '58', occupant: 'OLIVIER LUTONADIO', typeMaison: 'Twins' },
  { numero: '59', occupant: 'Antoine NZUNGU', typeMaison: 'Twins' },
  { numero: '60', occupant: 'Alidor Kankonde', typeMaison: 'Twins' },
  { numero: '61', occupant: '', typeMaison: 'Twins' },
  { numero: '62', occupant: 'Lucio', typeMaison: 'Twins' },
  { numero: '63', occupant: 'Alphonse Bindama', typeMaison: 'Twins' },
  { numero: '64', occupant: 'Dieu Merci NTUNGA', typeMaison: 'Twins' },
  { numero: '65', occupant: 'Hervé Milambu', typeMaison: 'Twins' },
  { numero: '68', occupant: 'Lundi ONOSAMBA', typeMaison: 'Twins' },
  { numero: '69', occupant: 'Patience Mansiamina', typeMaison: 'Twins' },
  { numero: '70', occupant: 'Philippe vangu', typeMaison: 'Twins' },
  { numero: '71', occupant: 'Moise KINZONZOLO', typeMaison: 'Twins' },
  { numero: '72', occupant: 'Marcel NGOY', typeMaison: 'Twins' },
  { numero: '73', occupant: 'Philippe DINANDI', typeMaison: 'Twins' },
  { numero: '74', occupant: 'Didier BAYISA', typeMaison: 'Twins' },
  { numero: '75', occupant: 'Dieu NGOMA Youri', typeMaison: 'Twins' },
];
